#!/bin/bash
cat $METEOR_HELPER_PATH/collectionTemplate.js | sed 's/MyCollection/'"${1^}"'/g;s/myCollection/'"$1"'/g' > lib/collections/$1.js
cat $METEOR_HELPER_PATH/collectionList.html | sed 's/MyCollection/'"${1^}"'/g;s/myCollection/'"$1"'/g' > client/views/$1List.html
cat $METEOR_HELPER_PATH/collectionList.js | sed 's/MyCollection/'"${1^}"'/g;s/myCollection/'"$1"'/g' > client/views/$1List.js
sed -i.bak '/<!--COLLECTIONS-->/a\<li><a href="{{urlFor '"'${1^}List'"'}}">'"${1^}"'</a></li>' client/views/common/navbar.html

